### ISSUE TITLE
Add CONTRIBUTORS.md

### ISSUE THREAD

**Issue by LasaleFamine** [LasaleFamine/polymer-lib-loader#1]

**Comment by anshuman73** [comment]
Hi ! I'd like to work on this !
Same specifications as regusabot or anything different ?

**Comment by LasaleFamine** [comment]
Hi @anshuman73,
the issue is strictly related to the CONTRIBUTING.md and not CONTRIBUTORS, but I like the idea.
So I'm changing the issue's name and I will open another issue for the CONTRIBUTING.md.

Thank you for your PR.

**Comment by anshuman73** [comment]
I never added a PR yet...

**Comment by LasaleFamine** [comment]
Hi @anshuman73, sorry but I made a mistake. 
I PR from another guy was related to this issue, I didn't check correctly. 

I saw your other PR for the CONTRIBUTING.md. I will check soon.

Thank you so much, and sorry again.

**Comment by anshuman73** [comment]
No issues :)
