### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by LasaleFamine** [LasaleFamine/polymer-lib-loader#3]

**Comment by ghost** [comment]
@LasaleFamine Hey I would like to do this, can you just point me how and where to look for manuals for contributing, I have never done this, I hope you help me, thanks in advance

**Comment by LasaleFamine** [comment]
Hello @knox97, sorry for the late reply and thank you for your interest.

Unfortunately I have received another PR yet and I think I will accept this one.
If you want to learn something about CONTRIBUTING you can check the PR related to this issue or the [Contributing guidelines](https://github.com/blog/1184-contributing-guidelines) of GitHub itself.

Thank you again.
